# Connect to your Driver

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).


In [ ]:
!unzip 'mammals.zip'

In [ ]:
cd /content/drive/MyDrive/GG Colab

/content/drive/MyDrive/GG Colab


In [ ]:
import cv2
import tensorflow as tf
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np
from tensorflow.keras.layers import Conv2D, MaxPooling2D, Flatten, Dense
from tensorflow.keras.models import Sequential

def VGG16(inputShape, numClasses):
    Model = Sequential()
    # Khoi 1
    Model.add(Conv2D(64, kernel_size=(3, 3), input_shape=inputShape, padding='same', activation='relu'))
    Model.add(Conv2D(64, kernel_size=(3, 3), activation='relu'))
    Model.add(MaxPooling2D(pool_size=(2, 2), strides=2))

    # Khoi 2:
    Model.add(Conv2D(128, kernel_size=(3, 3), activation='relu', padding='same'))
    Model.add(Conv2D(128, kernel_size=(3, 3), activation='relu', padding='same'))
    Model.add(MaxPooling2D(pool_size=(2, 2), strides=2))

    #Khoi 3
    Model.add(Conv2D(256, kernel_size=(3, 3), activation='relu', padding='same'))
    Model.add(Conv2D(256, kernel_size=(3, 3), activation='relu', padding='same'))
    Model.add(Conv2D(256, kernel_size=(3, 3), activation='relu', padding='same'))
    Model.add(MaxPooling2D(pool_size=(2, 2), strides=2))

    #Khoi 4
    Model.add(Conv2D(512, kernel_size=(3, 3), activation='relu', padding='same'))
    Model.add(Conv2D(512, kernel_size=(3, 3), activation='relu', padding='same'))
    Model.add(Conv2D(512, kernel_size=(3, 3), activation='relu', padding='same'))
    Model.add(MaxPooling2D(pool_size=(2, 2), strides=2))

    #Khoi 5
    Model.add(Conv2D(512, kernel_size=(3, 3), activation='relu', padding='same'))
    Model.add(Conv2D(512, kernel_size=(3, 3), activation='relu', padding='same'))
    Model.add(Conv2D(512, kernel_size=(3, 3), activation='relu', padding='same'))
    Model.add(MaxPooling2D(pool_size=(2, 2), strides=2))

    Model.add(Flatten())
    Model.add(Dense(4096, activation='relu'))
    Model.add(Dense(4096, activation='relu'))
    Model.add(Dense(numClasses, activation='softmax'))

    return Model



# imgs = []
# labels = []
# import os
# for x in os.listdir('mammals'):
#     label = x
#     for y in os.listdir(f'mammals/{x}'):
#         img = cv2.imread(f'mammals/{x}/{y}')
#         img = cv2.resize(img, (256, 256))
#         imgs.append(img)
#         labels.append(label)

# imgs = np.array(imgs)
# labels = np.array(labels)
# print(imgs.shape)

# from tensorflow.keras.utils import to_categorical
# from sklearn.model_selection import train_test_split
# from sklearn.preprocessing import LabelEncoder
# LB = LabelEncoder()
# labels = LB.fit_transform(labels)
# numClasses = len(np.unique(labels))
# labels = to_categorical(labels)
# Xtrain, Xtest, ytrain, ytest = train_test_split(imgs, labels, test_size=0.2)
# Xtrain = Xtrain.astype('float32')/255
# Xtest = Xtest.astype('float32')/255
# print(labels.shape)


# Model = getModel((256, 256, 3), numClasses)
# Model.summary()
# Model.compile(loss='categorical_crossentropy', optimizer='adam', metrics=['accuracy'])
# Model.fit(
#     Xtrain, ytrain, validation_data=(Xtest, ytest), epochs=15, batch_size=64, shuffle=True
# )
# result = Model.predict(np.array([img]).astype('float'))
# print(result)
# # for i in range(64):
# #     feature = result[0, :, :, i]
# #     ax = plt.subplot(8, 8, i+1)
# #     ax.set_xticks([])
# #     ax.set_yticks([])
# #     plt.imshow(feature, cmap='gray')
print("Succesfully")





Succesfully


In [ ]:
path ='/content/drive/MyDrive/GG Colab/mammals'
import os
imgs = []
labels = []
for x in os.listdir(path):
    label = x
    x1 = f'{path}/{x}'
    for y in os.listdir(x1):
        imgPath = f'{path}/{x}/{y}'
        img = cv2.imread(imgPath)
        imgs.append(img)
        labels.append(label)

imgTest = imgs[100]
labelTest = labels[100]
Nhan = labels

from tensorflow.keras.utils import to_categorical
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder

numClasses = len(np.unique(labels))
imgs = np.array(imgs)
labels = LabelEncoder().fit_transform(labels)
labels = to_categorical(labels, numClasses)
print(labels)


Xtrain, Xtest, ytrain, ytest = train_test_split(imgs, labels, test_size=0.2)
Xtest = np.array(Xtest).astype('float')/255
Xtrain = np.array(Xtrain).astype('float')/255
ytrain = np.array(ytrain)
ytest = np.array(ytest)
inputShape = (256, 256, 3)



[[0. 0. 0. ... 0. 1. 0.]
 [0. 0. 0. ... 0. 1. 0.]
 [0. 0. 0. ... 0. 1. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]


In [ ]:
Model = VGG16(inputShape, numClasses)
Model.compile(loss='categorical_crossentropy', optimizer='adam', metrics=['accuracy'])
Model.summary()

Model: "sequential_2"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 conv2d_26 (Conv2D)          (None, 256, 256, 64)      1792      
                                                                 
 conv2d_27 (Conv2D)          (None, 254, 254, 64)      36928     
                                                                 
 max_pooling2d_10 (MaxPooli  (None, 127, 127, 64)      0         
 ng2D)                                                           
                                                                 
 conv2d_28 (Conv2D)          (None, 127, 127, 128)     73856     
                                                                 
 conv2d_29 (Conv2D)          (None, 127, 127, 128)     147584    
                                                                 
 max_pooling2d_11 (MaxPooli  (None, 63, 63, 128)       0         
 ng2D)                                                

In [ ]:
H = Model.fit(Xtrain, ytrain, validation_data=(Xtest, ytest), epochs = 10)

In [ ]:
Model.save('VGG16Model.h5')

In [ ]:
from tensorflow.keras.models import load_model

In [ ]:
ModelLoad = load_model('VGG16Model.h5')

In [ ]:
result = ModelLoad.predict(np.array([imgTest]).astype('float'))
kq = np.argmax(result)
print(Nhan[kq])

Google Colab, Kaggle không train được:))))